#!/usr/bin/env python3
# coding: utf-8

import importlib
import sys
import os
import subprocess


UNYOHUB_COMMANDS_APP_NAME = "鉄道運用Hub コマンドラインツール"
UNYOHUB_COMMANDS_VERSION = "24.12-1"

UNYOHUB_DATA_DIR = "../data"


def mes (log_text, is_error=False, is_heading=False):
    if is_error:
        print("\x1b[31m\x1b[1m【エラー】\x1b[22m" + str(log_text) + "\x1b[0m")
    elif is_heading:
        print("\n\x1b[94m_/_/_/_/\x1b[0m " + str(log_text) + " \x1b[94m_/_/_/_/\x1b[0m\n")
    else:
        print(str(log_text))


print(UNYOHUB_COMMANDS_APP_NAME + " \x1b[90mv" + UNYOHUB_COMMANDS_VERSION + "\x1b[0m")

os.chdir(os.path.dirname(os.path.abspath(__file__)))
data_dir = (os.path.abspath(UNYOHUB_DATA_DIR))

args = sys.argv

if len(args) >= 2:
    match args[1]:
        case "setup-libs":
            if len(args) == 3:
                subprocess.run(["php", "modules/libs_setup.php", args[2]])
            else:
                subprocess.run(["php", "modules/libs_setup.php", "unyohub_admin"])
        case "conv-formations":
            if len(args) == 3:
                convert_formation_table = importlib.import_module("modules.convert_formation_table")
                convert_formation_table.convert_formation_table(mes, data_dir + "/" + os.path.basename(args[2]))
            else:
                print("\x1b[31m引数の数が異常です\x1b[0m")
        case "update-operations":
            if len(args) == 5:
                write_operations_to_db = importlib.import_module("modules.write_operations_to_db")
                write_operations_to_db.write_operations_to_db(mes, data_dir + "/" + os.path.basename(args[2]), os.path.basename(args[3]), os.path.basename(args[4]))
            else:
                print("\x1b[31m引数の数が異常です\x1b[0m")
        case "init-db":
            if len(args) == 3:
                initialize_db = importlib.import_module("modules.initialize_db")
                initialize_db.initialize_db(mes, data_dir + "/" + os.path.basename(args[2]))
            else:
                print("\x1b[31m引数の数が異常です\x1b[0m")
        case "init-moderation-db":
            initialize_moderation_db = importlib.import_module("modules.initialize_moderation_db")
            initialize_moderation_db.initialize_moderation_db(mes, os.path.dirname(data_dir) + "/config/moderation.db")
        case _:
            print("\x1b[31mコマンド \x1b[1m" + args[1] + "\x1b[22m は存在しません\x1b[0m")
else:
    print("\x1b[33mコマンドライン引数を指定してください\x1b[0m")
